# Execute your favorite apps at launch
exec-once = waybar
exec-once = wpaperd -d
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = swaync
exec-once = /home/val/.config/hypr/conf/scripts/checklid.sh
exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = elecwhat
exec-once = Telegram


# Load configuration from ML4W Hyprland Settings App
# exec = ~/.config/ml4w-hyprland-settings/hyprctl.sh
