[[manager.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = "<F2>"
run = "plugin toggle-pane min-parent"
desc = "Toggle the parent pane"

[[manager.prepend_keymap]]
on = "<F3>"
run = "plugin toggle-pane min-preview"
desc = "Toggle the preview pane"

[[manager.prepend_keymap]]
on   = "F"
run  = "filter --smart"
desc = "Filter"

[[manager.prepend_keymap]]
on = "l"
run = "plugin augment-command -- enter"
desc = "Enter a directory and skip directories with only a single subdirectory"

[[manager.prepend_keymap]]
on = "<RIGHT>"
run = "plugin augment-command -- enter"
desc = "Enter a directory and skip directories with only a single subdirectory"

[[manager.prepend_keymap]]
on = "<ENTER>"
run = "plugin augment-command -- enter"
desc = "Enter a directory and skip directories with only a single subdirectory"

[[manager.prepend_keymap]]
on = "o"
run = "disable"
desc = ""

[[input.prepend_keymap]]
on   = "<Up>"
run  = "mgr:arrow prev"
desc = ""

[[input.prepend_keymap]]
on   = "<Down>"
run  = "mgr:arrow next"
desc = ""

[[input.prepend_keymap]]
on   = "<Right>"
run  = ["input:close", "mgr:plugin augment-command -- enter"]
desc = ""

