Net/ThemeName "catppuccin-mocha-mauve-standard+default"
Net/IconThemeName "Adwaita"
Gtk/CursorThemeName "Bibata-Modern-Classic"
Net/EnableEventSounds 0
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 0
Xft/HintStyle "hintnone"
Xft/RGBA "rgb"
